name: Mirror to Client Repository

# Triggers when you push to main branch
on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for proper mirroring

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: Add client repository as remote
        run: |
          git remote add mirror git@github.com:sbeug/beuglab.com.git 

      - name: Push to client repository
        run: |
          git push mirror main --force

      - name: Push tags to client repository
        run: |
          git push mirror --tags --force
